### PR TITLE
Support avatar to be buffer

### PR DESCRIPTION
**Pull request by nr23730**
Solves #58.

I think Buffer is an appropriate alternative to URL. It works more like the uploading for images or attachments.

### CODE REVIEW

**Comment by nr23730** [comment]
Apparently not. 
For me (Signal bridge, but should be same for all other bridges) the setGhostAvatar function is just called once at startup when I add all my contacts to the status room and after this only for single contacts when they update their profile (avatar, name, etc.).

**Comment by twouters** [comment]
In that case: nice!

@thomas-profitt just looking at the diff, this change seems fine.
I'll give it a try on my setup to see if anything awful comes up.

**Comment by twouters** [comment]
fyi - been running with this patch for ~2 weeks and nothing broke so far.

**Comment by thomas-profitt** [comment]
Thanks for the contribution!

And @twouters, thanks again for testing.

**Pull request merged**
