### PR TITLE
[WIP] set room direct

### PR DESCRIPTION
**Pull request by nr23730**
Rebase of #52

### CODE REVIEW

**Comment by nr23730** [comment]
There is some stuff that I want to fix here. Right now for existing rooms the bot does not leave the room.

**Comment by thomas-profitt** [comment]
Thanks for moving this forward! This is one of the more important features the bridges lack.

**Comment by thomas-profitt** [comment]
And thank you @mijofa for your work on this!

**Comment by mijofa** [comment]
No worries, glad to see it's gotten merged in. :)
I'll get back to setting up my Matrix server eventually, it got put on the backburner due to some other projects taking priority.

**Pull request merged**
